# Generated by Django 4.0.4 on 2024-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0003_remove_product_hall'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='amount',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
