# Generated by Django 4.0.4 on 2024-02-14 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0004_clientorder_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientOrder',
            new_name='OrderItem',
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_order', to='django_telegram.client')),
                ('products', models.ManyToManyField(to='django_telegram.orderitem')),
            ],
        ),
    ]
