# Generated by Django 4.0.4 on 2024-02-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_telegram', '0006_rename_products_order_order_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='price_one_hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='price_thirty_minute',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='price_unlimited',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
